---
version: "3.8"
services:
  movies:
    image: sidd7/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: sidd7/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: sidd7/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: sidd7/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
